/**
 * Generated by Falang
 * Global functions
 **/
export interface Apis {
  GameApi: GameApi
}
export interface FalangGlobal {
  apis: Apis;
}
import { GameApi } from './GameApi';

export interface IExpressionFunctions {
  sin(p0: number): number;
  random(): number;
}


