/**
 * Generated by Falang
 * Document: clearScreen
 * Id: MfN5AOPHfZqUJ2ngOu3-Z
 **/
import { FalangGlobal } from './_falang';
import { GameState } from './State';
import { DrawPoints } from './DrawPoints';
// f:+icon:function:XhClfyJF7x2w7pFQxy4O_
/**
 * 
 **/
export interface IclearScreenParams {
  state: GameState;
  _falangGlobal: FalangGlobal;
}
export async function clearScreen(_params: IclearScreenParams): Promise<void> {
  const _falangGlobal = _params._falangGlobal;
  let state: GameState = JSON.parse(JSON.stringify(_params.state));
  // f:+icon:call_api:bXiI5Jw1fSTQY0GMDdYVH
  await _falangGlobal.apis.GameApi.Drawing.DrawRect({
    x: 0,
    y: 0,
    w: state.config.cellSize * state.config.gameWidth,
    h: state.config.cellSize * state.config.gameHeight,
    color: state.colors.backgroundColor,
  });
  // f:-icon:call_api:bXiI5Jw1fSTQY0GMDdYVH
  // f:+icon:call_function:o8jolrJTPtrTu0_tgxsYc
  await DrawPoints({
    _falangGlobal,
    state: state,
  });
  // f:-icon:call_function:o8jolrJTPtrTu0_tgxsYc
}
// f:-icon:function:XhClfyJF7x2w7pFQxy4O_

