/**
 * Generated by Falang
 * Document: DrawFood
 * Id: gFRB0Owe8fCqXE8tUqgfN
 **/
import { FalangGlobal } from './_falang';
import { GameState } from './State';
// f:+icon:function:52uYxdCVKxGQj9iZAv5Iw
/**
 * 
 **/
export interface IDrawFoodParams {
  state: GameState;
  _falangGlobal: FalangGlobal;
}
export async function DrawFood(_params: IDrawFoodParams): Promise<void> {
  const _falangGlobal = _params._falangGlobal;
  let state: GameState = JSON.parse(JSON.stringify(_params.state));
  // f:+icon:call_api:CzavJabM-Qart76uOglVG
  await _falangGlobal.apis.GameApi.Drawing.DrawCircle({
    x: state.food.x * state.config.cellSize + 1 / 2 + state.config.cellSize / 2,
    y: state.food.y * state.config.cellSize + state.config.cellSize / 2,
    r: state.config.foodSize,
    color: state.colors.foodColor,
  });
  // f:-icon:call_api:CzavJabM-Qart76uOglVG
}
// f:-icon:function:52uYxdCVKxGQj9iZAv5Iw

