/**
 * Generated by Falang
 * Document: drawSnakeSquare
 * Id: JWQudFlU2WMpaPUF9FajM
 **/
import { FalangGlobal } from './_falang';
import { Point } from './State';
import { Color } from './State';
import { Config } from './State';
// f:+icon:function:K26d9OrusDeFwiQif8nMs
/**
 * 
 **/
export interface IdrawSnakeSquareParams {
  point: Point;
  color: Color;
  config: Config;
  _falangGlobal: FalangGlobal;
}
export async function drawSnakeSquare(_params: IdrawSnakeSquareParams): Promise<void> {
  const _falangGlobal = _params._falangGlobal;
  let point: Point = JSON.parse(JSON.stringify(_params.point));
  let color: Color = JSON.parse(JSON.stringify(_params.color));
  let config: Config = JSON.parse(JSON.stringify(_params.config));
  // f:+icon:call_api:inPlwfqnVyKbuKIARZ0aK
  await _falangGlobal.apis.GameApi.Drawing.DrawRect({
    x: point.x * config.cellSize,
    y: point.y * config.cellSize,
    w: config.cellSize - 2,
    h: config.cellSize - 2,
    color: color,
  });
  // f:-icon:call_api:inPlwfqnVyKbuKIARZ0aK
}
// f:-icon:function:K26d9OrusDeFwiQif8nMs

