/**
 * Generated by Falang
 * Document: DrawPoints
 * Id: 3LZtjpTblw_H7rDb6RJA8
 **/
import { FalangGlobal } from './_falang';
import { GameState } from './State';
// f:+icon:function:qIMuqdtmy4VhfBtzzn_Y6
/**
 * 
 **/
export interface IDrawPointsParams {
  state: GameState;
  _falangGlobal: FalangGlobal;
}
export async function DrawPoints(_params: IDrawPointsParams): Promise<void> {
  const _falangGlobal = _params._falangGlobal;
  let state: GameState = JSON.parse(JSON.stringify(_params.state));
  // f:+icon:from_to_cycle:NMAD8IjxsiYIZ26tQkduC
  const _x_from = 0;
  const _x_to = state.config.gameWidth;
  for (let x = _x_from; x < _x_to; x++) {
    // f:+icon:from_to_cycle:CjO68yBYiYPdk9yF7TuLA
    const _y_from = 0;
    const _y_to = state.config.gameHeight;
    for (let y = _y_from; y < _y_to; y++) {
      // f:+icon:call_api:cklvoGUX8mIQ7e9igqENi
      await _falangGlobal.apis.GameApi.Drawing.DrawCircle({
        x: x * state.config.cellSize + state.config.cellSize / 2,
        y: y * state.config.cellSize + state.config.cellSize / 2,
        r: state.config.pointRadius,
        color: state.colors.pointColor,
      });
      // f:-icon:call_api:cklvoGUX8mIQ7e9igqENi
    }
    // f:-icon:from_to_cycle:CjO68yBYiYPdk9yF7TuLA
  }
  // f:-icon:from_to_cycle:NMAD8IjxsiYIZ26tQkduC
}
// f:-icon:function:qIMuqdtmy4VhfBtzzn_Y6

