/**
 * Generated by Falang
 * Document: GameApi
 * Id: ucuAXFssAyGB1IV3QV_Nh
 **/
import { ButtonsState } from './State';
import { Color } from './State';
// f:+icon:logic_external_apis:IXPTCilqzAuOKyR3fWJRB
export interface IGetButtonsStateParams {
}
export interface ISleepParams {
}
export interface IGetRandomParams {
  min: number;
  max: number;
}
export interface Application {
  GetButtonsState (params: IGetButtonsStateParams): Promise<ButtonsState>;
  Sleep (params: ISleepParams): Promise<void>;
  GetRandom (params: IGetRandomParams): Promise<number>;
}
export interface IDrawRectParams {
  x: number;
  y: number;
  w: number;
  h: number;
  color: Color;
}
export interface IDrawCircleParams {
  x: number;
  y: number;
  r: number;
  color: Color;
}
export interface Drawing {
  DrawRect (params: IDrawRectParams): Promise<void>;
  DrawCircle (params: IDrawCircleParams): Promise<void>;
}
export interface GameApi {
  Application: Application,
  Drawing: Drawing,
}
// f:-icon:logic_external_apis:IXPTCilqzAuOKyR3fWJRB

