/**
 * Generated by Falang
 * Document: getColors
 * Id: LHTslQF9bzoqB6XSC1quV
 **/
import { FalangGlobal } from './_falang';
import { Colors } from './State';
// f:+icon:function:b0DLl_wFtqSjCFgZlOo64
/**
 * 
 **/
export interface IgetColorsParams {
  _falangGlobal: FalangGlobal;
}
export async function getColors(_params: IgetColorsParams): Promise<Colors> {
  const _falangGlobal = _params._falangGlobal;
  let returnValue: Colors = {foodColor:{r:0,g:0,b:0},cellColor:{r:0,g:0,b:0},pointColor:{r:0,g:0,b:0},backgroundColor:{r:0,g:0,b:0}};
  // f:+icon:assign_var:CcfLFSMw7P_XUpMqTcSAp
  returnValue.foodColor.r = 255;
  // f:-icon:assign_var:CcfLFSMw7P_XUpMqTcSAp
  // f:+icon:assign_var:ZW9bxgwEIwlNZ-ukPcnni
  returnValue.cellColor.g = 255;
  // f:-icon:assign_var:ZW9bxgwEIwlNZ-ukPcnni
  // f:+icon:assign_var:VzhtTbeVFVh4ZvXcSdsj5
  returnValue.pointColor.r = 50;
  // f:-icon:assign_var:VzhtTbeVFVh4ZvXcSdsj5
  // f:+icon:assign_var:4QfZ0-hyon6tYQ6xsAnQR
  returnValue.pointColor.g = 50;
  // f:-icon:assign_var:4QfZ0-hyon6tYQ6xsAnQR
  // f:+icon:assign_var:BICP6FBwsBZOGOlYz-HCE
  returnValue.pointColor.b = 50;
  // f:-icon:assign_var:BICP6FBwsBZOGOlYz-HCE
  return returnValue;
}
// f:-icon:function:b0DLl_wFtqSjCFgZlOo64

