/**
 * Generated by Falang
 * Document: getNextPoint
 * Id: nOyebu5dibPnEZ5ts2H2M
 **/
import { FalangGlobal } from './_falang';
import { GameState } from './State';
import { Point } from './State';
// f:+icon:function:SwH6HqGCKAdnPQFBpMc2L
/**
 * 
 **/
export interface IgetNextPointParams {
  state: GameState;
  _falangGlobal: FalangGlobal;
}
export async function getNextPoint(_params: IgetNextPointParams): Promise<Point> {
  const _falangGlobal = _params._falangGlobal;
  let state: GameState = JSON.parse(JSON.stringify(_params.state));
  let returnValue: Point = {x:0,y:0};
  // f:+icon:assign_var:rP9rN4kFsHGfJpGpniSPO
  returnValue.x = state.snake.x + state.snake.dirX;
  // f:-icon:assign_var:rP9rN4kFsHGfJpGpniSPO
  // f:+icon:assign_var:vueysL3Jwfa8zveAFJMx8
  returnValue.y = state.snake.y + state.snake.dirY;
  // f:-icon:assign_var:vueysL3Jwfa8zveAFJMx8
  // f:+icon:if:MIvkhNpZFOww2JZVcfSQt
  if (returnValue.x < 0) {
    // f:+icon:assign_var:kkgTGQ1_zG-zFH2WtY3B7
    returnValue.x = state.config.gameWidth - 1;
    // f:-icon:assign_var:kkgTGQ1_zG-zFH2WtY3B7
  } else {
  }
  // f:-icon:if:MIvkhNpZFOww2JZVcfSQt
  // f:+icon:if:X-eA6y5FWhxhObYVZhawl
  if (returnValue.x >= state.config.gameWidth) {
    // f:+icon:assign_var:qhGMOpiAbh5PSSWpyw7LM
    returnValue.x = 0;
    // f:-icon:assign_var:qhGMOpiAbh5PSSWpyw7LM
  } else {
  }
  // f:-icon:if:X-eA6y5FWhxhObYVZhawl
  // f:+icon:if:JWJofF7EZoLjDj809MdIj
  if (returnValue.y < 0) {
    // f:+icon:assign_var:I6JlOjQVEDHriJmb7nm4h
    returnValue.y = state.config.gameHeight - 1;
    // f:-icon:assign_var:I6JlOjQVEDHriJmb7nm4h
  } else {
  }
  // f:-icon:if:JWJofF7EZoLjDj809MdIj
  // f:+icon:if:5babAoFjRXNlUyLoOc2S-
  if (returnValue.y >= state.config.gameHeight) {
    // f:+icon:assign_var:tg0yRV4m0fEACjAKzEvQ8
    returnValue.y = 0;
    // f:-icon:assign_var:tg0yRV4m0fEACjAKzEvQ8
  } else {
  }
  // f:-icon:if:5babAoFjRXNlUyLoOc2S-
  return returnValue;
}
// f:-icon:function:SwH6HqGCKAdnPQFBpMc2L

