/**
 * Generated by Falang
 * Document: getRandomPoint
 * Id: 9r_4NfSsuYqbP9ScYSYBR
 **/
import { FalangGlobal } from './_falang';
import { GameState } from './State';
import { Point } from './State';
// f:+icon:function:p1oTmW4T5DPD-s9IIoGwU
/**
 * 
 **/
export interface IgetRandomPointParams {
  state: GameState;
  _falangGlobal: FalangGlobal;
}
export async function getRandomPoint(_params: IgetRandomPointParams): Promise<Point> {
  const _falangGlobal = _params._falangGlobal;
  let state: GameState = JSON.parse(JSON.stringify(_params.state));
  let returnValue: Point = {x:0,y:0};
  // f:+icon:call_api:QoxOq5QmBL289JWVnNsa_
  let x: number = await _falangGlobal.apis.GameApi.Application.GetRandom({
    min: 0,
    max: state.config.gameWidth,
  });
  // f:-icon:call_api:QoxOq5QmBL289JWVnNsa_
  // f:+icon:call_api:1zE6iGn9WUdhq57-K0gSH
  let y: number = await _falangGlobal.apis.GameApi.Application.GetRandom({
    min: 0,
    max: state.config.gameHeight,
  });
  // f:-icon:call_api:1zE6iGn9WUdhq57-K0gSH
  // f:+icon:assign_var:01k6Xc4_S5yNpF2tNLrvx
  returnValue.x = x;
  // f:-icon:assign_var:01k6Xc4_S5yNpF2tNLrvx
  // f:+icon:assign_var:JGK4-Dkom4nLbELAh_HWX
  returnValue.y = y;
  // f:-icon:assign_var:JGK4-Dkom4nLbELAh_HWX
  return returnValue;
}
// f:-icon:function:p1oTmW4T5DPD-s9IIoGwU

