/**
 * Generated by Falang
 * Document: main
 * Id: m7pVTfZRXeP0bT6BWlmQf
 **/
import { FalangGlobal } from './_falang';
import { Config } from './State';
import { GameState } from './State';
import { getColors } from './getColors';
import { Colors } from './State';
import { getRandomPoint } from './getRandomPoint';
import { Point } from './State';
import { getNewFoodPoint } from './getNewFoodPoint';
import { clearScreen } from './clearScreen';
import { DrawFood } from './DrawFood';
import { drawSnakeSquare } from './drawSnakeSquare';
import { ButtonsState } from './State';
import { getNextPoint } from './getNextPoint';
import { isGameOver } from './isGameOver';
// f:+icon:function:lB5upikdDh_HbhKEy2jH0
/**
 * 
 **/
export interface ImainParams {
  config: Config;
  _falangGlobal: FalangGlobal;
}
export async function main(_params: ImainParams): Promise<void> {
  const _falangGlobal = _params._falangGlobal;
  let config: Config = JSON.parse(JSON.stringify(_params.config));
  // f:+icon:create_var:PL1ygW9jTUqSOjf0qD5cf
  let state: GameState = {colors:{foodColor:{r:0,g:0,b:0},cellColor:{r:0,g:0,b:0},pointColor:{r:0,g:0,b:0},backgroundColor:{r:0,g:0,b:0}},snake:{x:0,y:0,dirX:0,dirY:0,body:[]},food:{x:0,y:0},config:{cellSize:0,foodSize:0,pointRadius:0,gameWidth:0,gameHeight:0}};
  // f:-icon:create_var:PL1ygW9jTUqSOjf0qD5cf
  // f:+icon:assign_var:Th_Mpjao_oLzpEoRTVOJV
  state.config = config;
  // f:-icon:assign_var:Th_Mpjao_oLzpEoRTVOJV
  // f:+icon:call_function:coMU79dt42juxXxaI9V0v
  let newColors: Colors = await getColors({
    _falangGlobal,
  });
  // f:-icon:call_function:coMU79dt42juxXxaI9V0v
  // f:+icon:assign_var:fda4Yx38op-Pn320kZ_6v
  state.colors = newColors;
  // f:-icon:assign_var:fda4Yx38op-Pn320kZ_6v
  // f:+icon:call_function:nOIj_tm-8R6736W1G7rjN
  let snakePoint: Point = await getRandomPoint({
    _falangGlobal,
    state: state,
  });
  // f:-icon:call_function:nOIj_tm-8R6736W1G7rjN
  // f:+icon:assign_var:xHRB4msL6yFfuxGSolU3G
  state.snake.x = snakePoint.x;
  // f:-icon:assign_var:xHRB4msL6yFfuxGSolU3G
  // f:+icon:assign_var:_oMa_qBHodtiQ4yEPqpa9
  state.snake.y = snakePoint.y;
  // f:-icon:assign_var:_oMa_qBHodtiQ4yEPqpa9
  // f:+icon:call_function:EhpuZbl6e0pnIeusCa_5M
  let foodPoint: Point = await getNewFoodPoint({
    _falangGlobal,
    state: state,
  });
  // f:-icon:call_function:EhpuZbl6e0pnIeusCa_5M
  // f:+icon:assign_var:_DlmnAOHP64qjn_EByQNh
  state.food = foodPoint;
  // f:-icon:assign_var:_DlmnAOHP64qjn_EByQNh
  // f:+icon:arr_push:OBURwlMvvVzKS56ghPw54
  state.snake.body.push(snakePoint)
  // f:-icon:arr_push:OBURwlMvvVzKS56ghPw54
  // f:+icon:call_function:eBkdfxI8XgcEG6gW_bbKD
  await clearScreen({
    _falangGlobal,
    state: state,
  });
  // f:-icon:call_function:eBkdfxI8XgcEG6gW_bbKD
  // f:+icon:call_function:Wnjqt6u201-28OxXrjqIF
  await DrawFood({
    _falangGlobal,
    state: state,
  });
  // f:-icon:call_function:Wnjqt6u201-28OxXrjqIF
  // f:+icon:call_function:n7geuiwQBL18fzr6wSd7E
  await drawSnakeSquare({
    _falangGlobal,
    point: snakePoint,
    color: state.colors.cellColor,
    config: state.config,
  });
  // f:-icon:call_function:n7geuiwQBL18fzr6wSd7E
  // f:+icon:while:LVIjyQVeO9DbTqBLWS4QN
  do {
    // f:+icon:call_api:OTH3M7nL6TwI2m6UqC_uq
    await _falangGlobal.apis.GameApi.Application.Sleep({
    });
    // f:-icon:call_api:OTH3M7nL6TwI2m6UqC_uq
    // f:+icon:call_api:73HZd8WnmnnaowYkSyW2Y
    let buttons: ButtonsState = await _falangGlobal.apis.GameApi.Application.GetButtonsState({
    });
    // f:-icon:call_api:73HZd8WnmnnaowYkSyW2Y
    // f:+icon:if:N3P--yhZiBDqmqpPO9ZaL
    if (buttons.left) {
      // f:+icon:if:20ZJL1qnLFgtA471QN1nm
      if (state.snake.dirX == 1) {
      } else {
        // f:+icon:assign_var:lsKFPHiFUnvBV8xZQYqRs
        state.snake.dirX = -1;
        // f:-icon:assign_var:lsKFPHiFUnvBV8xZQYqRs
        // f:+icon:assign_var:g02JFtOlwKkKeDKyb8iH2
        state.snake.dirY = 0;
        // f:-icon:assign_var:g02JFtOlwKkKeDKyb8iH2
      }
      // f:-icon:if:20ZJL1qnLFgtA471QN1nm
    } else {
      // f:+icon:if:kUtdEpABwwB3FknbIIlYi
      if (buttons.right) {
        // f:+icon:if:xPkvSV53hUz6pJxFRFeG9
        if (state.snake.dirX == -1) {
        } else {
          // f:+icon:assign_var:xiWo2aSAyaSAAeXILMzIE
          state.snake.dirX = 1;
          // f:-icon:assign_var:xiWo2aSAyaSAAeXILMzIE
          // f:+icon:assign_var:guBRV_MOEO6dbL-ZOlhk9
          state.snake.dirY = 0;
          // f:-icon:assign_var:guBRV_MOEO6dbL-ZOlhk9
        }
        // f:-icon:if:xPkvSV53hUz6pJxFRFeG9
      } else {
        // f:+icon:if:Ah1YgblPJpw6h5fKYsYa1
        if (buttons.top) {
          // f:+icon:if:4JFaZJSrvfDVbhDRaarp6
          if (state.snake.dirY == 1) {
          } else {
            // f:+icon:assign_var:S8dQHEOvfnZXgXNaYJQC_
            state.snake.dirX = 0;
            // f:-icon:assign_var:S8dQHEOvfnZXgXNaYJQC_
            // f:+icon:assign_var:Ox3hhZRJfg5FMflfFY1fF
            state.snake.dirY = -1;
            // f:-icon:assign_var:Ox3hhZRJfg5FMflfFY1fF
          }
          // f:-icon:if:4JFaZJSrvfDVbhDRaarp6
        } else {
          // f:+icon:if:z4HPvsk14oGd6gHgAjt7P
          if (buttons.bottom) {
            // f:+icon:if:csOMo5j2PD6An5PwEohKm
            if (state.snake.dirY == -1) {
            } else {
              // f:+icon:assign_var:71w6gNOkzKiPSYNUWLWjT
              state.snake.dirX = 0;
              // f:-icon:assign_var:71w6gNOkzKiPSYNUWLWjT
              // f:+icon:assign_var:_7GjktgNfrD9E5efh77tA
              state.snake.dirY = 1;
              // f:-icon:assign_var:_7GjktgNfrD9E5efh77tA
            }
            // f:-icon:if:csOMo5j2PD6An5PwEohKm
          } else {
          }
          // f:-icon:if:z4HPvsk14oGd6gHgAjt7P
        }
        // f:-icon:if:Ah1YgblPJpw6h5fKYsYa1
      }
      // f:-icon:if:kUtdEpABwwB3FknbIIlYi
    }
    // f:-icon:if:N3P--yhZiBDqmqpPO9ZaL
    // f:+icon:if:BjtdWWmhwWBdMi4lJa4EW
    if (state.snake.dirX == 0 && state.snake.dirY == 0) {
      continue;
    } else {
    }
    // f:-icon:if:BjtdWWmhwWBdMi4lJa4EW
    // f:+icon:call_function:y-82umpcjj0E7E0aBNTDm
    let nextPoint: Point = await getNextPoint({
      _falangGlobal,
      state: state,
    });
    // f:-icon:call_function:y-82umpcjj0E7E0aBNTDm
    // f:+icon:assign_var:pXy2D1myY3LaVRIJSAupb
    state.snake.x = nextPoint.x;
    // f:-icon:assign_var:pXy2D1myY3LaVRIJSAupb
    // f:+icon:assign_var:IlIanWUjpVergZAeeiZm2
    state.snake.y = nextPoint.y;
    // f:-icon:assign_var:IlIanWUjpVergZAeeiZm2
    // f:+icon:call_function:f9UwUDTP1olgYfu5K74hm
    let isOver: boolean = await isGameOver({
      _falangGlobal,
      state: state,
    });
    // f:-icon:call_function:f9UwUDTP1olgYfu5K74hm
    // f:+icon:if:7_4sZYSpK5CzmHEIvLWLg
    if (isOver) {
      // f:+icon:assign_var:dPjGRiBJLvEeDTX5xbzHu
      state.snake.dirX = 0;
      // f:-icon:assign_var:dPjGRiBJLvEeDTX5xbzHu
      // f:+icon:assign_var:9mwS3yc9mrNMP2M-P2sAS
      state.snake.dirY = 0;
      // f:-icon:assign_var:9mwS3yc9mrNMP2M-P2sAS
      // f:+icon:call_function:c65HhdmoFu1GpnNNWLWkB
      let newSnakePoint: Point = await getRandomPoint({
        _falangGlobal,
        state: state,
      });
      // f:-icon:call_function:c65HhdmoFu1GpnNNWLWkB
      // f:+icon:assign_var:leLkEbFVQW87YHakHfFAX
      state.snake.body = [ newSnakePoint ];
      // f:-icon:assign_var:leLkEbFVQW87YHakHfFAX
      // f:+icon:call_function:NM0MNlvryEsXtu58IKDgs
      let newFoodPoint: Point = await getNewFoodPoint({
        _falangGlobal,
        state: state,
      });
      // f:-icon:call_function:NM0MNlvryEsXtu58IKDgs
      // f:+icon:assign_var:578E6v0c9I0hRO6o1PDP-
      state.food = newFoodPoint;
      // f:-icon:assign_var:578E6v0c9I0hRO6o1PDP-
      // f:+icon:call_api:gMinsGFaFQQkv-SiXdT-6
      await _falangGlobal.apis.GameApi.Drawing.DrawRect({
        x: 0,
        y: 0,
        w: state.config.cellSize * state.config.gameWidth,
        h: state.config.cellSize * state.config.gameHeight,
        color: state.colors.foodColor,
      });
      // f:-icon:call_api:gMinsGFaFQQkv-SiXdT-6
      // f:+icon:call_function:vAg5y8j3yLm0eRIQollqL
      await clearScreen({
        _falangGlobal,
        state: state,
      });
      // f:-icon:call_function:vAg5y8j3yLm0eRIQollqL
      // f:+icon:call_function:oejSVBSOo4shgFcVcvqE4
      await DrawFood({
        _falangGlobal,
        state: state,
      });
      // f:-icon:call_function:oejSVBSOo4shgFcVcvqE4
      // f:+icon:call_function:LnM4pGU1fzaM7VEO8SQXD
      await drawSnakeSquare({
        _falangGlobal,
        point: newSnakePoint,
        color: state.colors.cellColor,
        config: state.config,
      });
      // f:-icon:call_function:LnM4pGU1fzaM7VEO8SQXD
    } else {
      // f:+icon:arr_unshift:GG75qN8xmI5WV4ATpE8Db
      state.snake.body.unshift(nextPoint)
      // f:-icon:arr_unshift:GG75qN8xmI5WV4ATpE8Db
      // f:+icon:call_function:d9Xp7CDH4kEYpSWrcd6S2
      await drawSnakeSquare({
        _falangGlobal,
        point: nextPoint,
        color: state.colors.cellColor,
        config: state.config,
      });
      // f:-icon:call_function:d9Xp7CDH4kEYpSWrcd6S2
      // f:+icon:if:J8FssgibapviRe1t0KXfw
      if (state.snake.x == state.food.x && state.snake.y == state.food.y) {
        // f:+icon:call_function:Naa9RR5i-Vl_AfGCf0jqz
        let newFoodPoint: Point = await getNewFoodPoint({
          _falangGlobal,
          state: state,
        });
        // f:-icon:call_function:Naa9RR5i-Vl_AfGCf0jqz
        // f:+icon:assign_var:pjozbbcGA5eFaGMIRd4tZ
        state.food = newFoodPoint;
        // f:-icon:assign_var:pjozbbcGA5eFaGMIRd4tZ
        // f:+icon:call_function:_kbNGeEvINMqUxodF4N6Z
        await DrawFood({
          _falangGlobal,
          state: state,
        });
        // f:-icon:call_function:_kbNGeEvINMqUxodF4N6Z
      } else {
        // f:+icon:arr_pop:GzFhOMMQf-nGEF0KwIHUZ
        let oldPoint = state.snake.body.pop()
        if (!oldPoint) throw new Error('');
        // f:-icon:arr_pop:GzFhOMMQf-nGEF0KwIHUZ
        // f:+icon:call_function:w49QyhSyqKkNDpzGmoRjy
        await drawSnakeSquare({
          _falangGlobal,
          point: oldPoint,
          color: state.colors.backgroundColor,
          config: state.config,
        });
        // f:-icon:call_function:w49QyhSyqKkNDpzGmoRjy
        // f:+icon:call_api:SrriDRS3uorPptX9WCEhs
        await _falangGlobal.apis.GameApi.Drawing.DrawCircle({
          x: oldPoint.x * state.config.cellSize + state.config.cellSize / 2,
          y: oldPoint.y * state.config.cellSize + state.config.cellSize / 2,
          r: state.config.pointRadius,
          color: state.colors.pointColor,
        });
        // f:-icon:call_api:SrriDRS3uorPptX9WCEhs
      }
      // f:-icon:if:J8FssgibapviRe1t0KXfw
    }
    // f:-icon:if:7_4sZYSpK5CzmHEIvLWLg
  } while (true);
  // f:-icon:while:LVIjyQVeO9DbTqBLWS4QN
}
// f:-icon:function:lB5upikdDh_HbhKEy2jH0

