/**
 * Generated by Falang
 * Document: DrawPoints
 * Id: 3LZtjpTblw_H7rDb6RJA8
 **/
#[allow(non_snake_case)]
#[allow(unused_mut)]
// f:+icon:function:qIMuqdtmy4VhfBtzzn_Y6
/**
 * 
 **/
pub fn DrawPoints(state: &crate::falang::State::GameState, _apis: &mut dyn crate::falang::falang_global::Apis) -> ()
{
  // f:+icon:from_to_cycle:NMAD8IjxsiYIZ26tQkduC
  let _x_from:i32 = (0) as i32;
  let _x_to:i32 = state.config.gameWidth;
  for x in _x_from.._x_to
  {
    // f:+icon:from_to_cycle:CjO68yBYiYPdk9yF7TuLA
    let _y_from:i32 = (0) as i32;
    let _y_to:i32 = state.config.gameHeight;
    for y in _y_from.._y_to
    {
      // f:+icon:call_api:cklvoGUX8mIQ7e9igqENi
      _apis.GameApi_Drawing_DrawCircle(x * state.config.cellSize + state.config.cellSize / (2) as i32, y * state.config.cellSize + state.config.cellSize / (2) as i32, state.config.pointRadius, &state.colors.pointColor);
      // f:-icon:call_api:cklvoGUX8mIQ7e9igqENi
    }
    // f:-icon:from_to_cycle:CjO68yBYiYPdk9yF7TuLA
  }
  // f:-icon:from_to_cycle:NMAD8IjxsiYIZ26tQkduC
  
}
// f:-icon:function:qIMuqdtmy4VhfBtzzn_Y6

