/**
 * Generated by Falang
 * Document: GameApi
 * Id: ucuAXFssAyGB1IV3QV_Nh
 **/
use crate::falang::State;
// f:+icon:logic_external_apis:IXPTCilqzAuOKyR3fWJRB
#[derive(Clone)]
pub struct IGetButtonsStateParams {
}
#[derive(Clone)]
pub struct ISleepParams {
  pub ms: i32,
}
pub trait Application
{
  fn GetButtonsState (&self, params: IGetButtonsStateParams) -> State::ButtonsState;
  fn Sleep (&self, params: ISleepParams) -> ();
}
#[derive(Clone)]
pub struct IDrawSquareParams {
  pub x: i32,
  pub y: i32,
  pub w: i32,
  pub h: i32,
  pub color: State::Color,
}
#[derive(Clone)]
pub struct IDrawCircleParams {
  pub x: i32,
  pub y: i32,
  pub r: i32,
  pub color: State::Color,
}
#[derive(Clone)]
pub struct IClearScreenParams {
}
pub trait Drawing
{
  fn DrawSquare (&self, params: IDrawSquareParams) -> ();
  fn DrawCircle (&self, params: IDrawCircleParams) -> ();
  fn ClearScreen (&self, params: IClearScreenParams) -> ();
}
#[derive(Clone)]
pub struct GameApi<'a> {
  pub Application: &'a dyn Application,
  pub Drawing: &'a dyn Drawing,
}
// f:-icon:logic_external_apis:IXPTCilqzAuOKyR3fWJRB

