/**
 * Generated by Falang
 * Document: getColors
 * Id: LHTslQF9bzoqB6XSC1quV
 **/
#[allow(non_snake_case)]
#[allow(unused_mut)]
// f:+icon:function:b0DLl_wFtqSjCFgZlOo64
/**
 * 
 **/
pub fn getColors(_apis: &mut dyn crate::falang::falang_global::Apis) -> crate::falang::State::Colors
{
  let mut returnValue: crate::falang::State::Colors = crate::falang::State::Colors::new();
  // f:+icon:assign_var:CcfLFSMw7P_XUpMqTcSAp
  returnValue.foodColor.r = (255) as i32;
  // f:-icon:assign_var:CcfLFSMw7P_XUpMqTcSAp
  // f:+icon:assign_var:ZW9bxgwEIwlNZ-ukPcnni
  returnValue.cellColor.g = (255) as i32;
  // f:-icon:assign_var:ZW9bxgwEIwlNZ-ukPcnni
  // f:+icon:assign_var:VzhtTbeVFVh4ZvXcSdsj5
  returnValue.pointColor.r = (50) as i32;
  // f:-icon:assign_var:VzhtTbeVFVh4ZvXcSdsj5
  // f:+icon:assign_var:4QfZ0-hyon6tYQ6xsAnQR
  returnValue.pointColor.g = (50) as i32;
  // f:-icon:assign_var:4QfZ0-hyon6tYQ6xsAnQR
  // f:+icon:assign_var:BICP6FBwsBZOGOlYz-HCE
  returnValue.pointColor.b = (50) as i32;
  // f:-icon:assign_var:BICP6FBwsBZOGOlYz-HCE
  
  returnValue
}
// f:-icon:function:b0DLl_wFtqSjCFgZlOo64

