/**
 * Generated by Falang
 * Document: getNewFoodPoint
 * Id: zdslcqgRu28Idy8zf--n8
 **/
#[allow(non_snake_case)]
#[allow(unused_mut)]
// f:+icon:function:UTXeesjId4EdZOMA35YW1
/**
 * 
 **/
pub fn getNewFoodPoint(state: &crate::falang::State::GameState, _apis: &mut dyn crate::falang::falang_global::Apis) -> crate::falang::State::Point
{
  let mut returnValue: crate::falang::State::Point = crate::falang::State::Point::new();
  let mut _continue_level: i8 = 0;
  // f:+icon:pseudo-cycle:DQZhz6wI53p8hPB7WPRAm
  loop {
    // f:+icon:call_function:nv69UdcCiiXZ3zQeoqpO5
    let mut newFoodPoint: crate::falang::State::Point = crate::falang::getRandomPoint::getRandomPoint(&state, _apis);
    // f:-icon:call_function:nv69UdcCiiXZ3zQeoqpO5
    // f:+icon:foreach:VckIcLeMDb4P6lC0ug7iX
    for bodyItem in state.snake.body.iter() {
      // f:+icon:if:-B1ubzcYAsKCnoIqg2OP1
      if newFoodPoint.x == bodyItem.x && newFoodPoint.y == bodyItem.y {
        _continue_level = 1;
        break;
      } else {
      }
      // f:-icon:if:-B1ubzcYAsKCnoIqg2OP1
    }
    if _continue_level > 1 { _continue_level-=1; break; }
    if _continue_level == 1 { _continue_level-=1; continue; }
    // f:-icon:foreach:VckIcLeMDb4P6lC0ug7iX
    // f:+icon:assign_var:eY2h0tVu6B07rv-r5R7qI
    returnValue.x = newFoodPoint.x;
    // f:-icon:assign_var:eY2h0tVu6B07rv-r5R7qI
    // f:+icon:assign_var:AOOJSmk-jdzqHSn472XDm
    returnValue.y = newFoodPoint.y;
    // f:-icon:assign_var:AOOJSmk-jdzqHSn472XDm
    break;
  }
  // f:-icon:pseudo-cycle:DQZhz6wI53p8hPB7WPRAm
  
  returnValue
}
// f:-icon:function:UTXeesjId4EdZOMA35YW1

