/**
 * Generated by Falang
 * Document: getRandomPoint
 * Id: 9r_4NfSsuYqbP9ScYSYBR
 **/
#[allow(non_snake_case)]
#[allow(unused_mut)]
// f:+icon:function:p1oTmW4T5DPD-s9IIoGwU
/**
 * 
 **/
pub fn getRandomPoint(state: &crate::falang::State::GameState, _apis: &mut dyn crate::falang::falang_global::Apis) -> crate::falang::State::Point
{
  let mut returnValue: crate::falang::State::Point = crate::falang::State::Point::new();
  // f:+icon:call_api:QoxOq5QmBL289JWVnNsa_
  let mut x: i32 = _apis.GameApi_Application_GetRandom((0) as i32, state.config.gameWidth);
  // f:-icon:call_api:QoxOq5QmBL289JWVnNsa_
  // f:+icon:call_api:1zE6iGn9WUdhq57-K0gSH
  let mut y: i32 = _apis.GameApi_Application_GetRandom((0) as i32, state.config.gameHeight);
  // f:-icon:call_api:1zE6iGn9WUdhq57-K0gSH
  // f:+icon:assign_var:01k6Xc4_S5yNpF2tNLrvx
  returnValue.x = x;
  // f:-icon:assign_var:01k6Xc4_S5yNpF2tNLrvx
  // f:+icon:assign_var:JGK4-Dkom4nLbELAh_HWX
  returnValue.y = y;
  // f:-icon:assign_var:JGK4-Dkom4nLbELAh_HWX
  
  returnValue
}
// f:-icon:function:p1oTmW4T5DPD-s9IIoGwU

