/**
 * Generated by Falang
 * Document: main
 * Id: m7pVTfZRXeP0bT6BWlmQf
 **/
#[allow(non_snake_case)]
#[allow(unused_mut)]
// f:+icon:function:lB5upikdDh_HbhKEy2jH0
/**
 * 
 **/
pub fn main(config: &crate::falang::State::Config, _apis: &mut dyn crate::falang::falang_global::Apis) -> ()
{
  // f:+icon:create_var:PL1ygW9jTUqSOjf0qD5cf
  let mut state: crate::falang::State::GameState = crate::falang::State::GameState::new();
  // f:-icon:create_var:PL1ygW9jTUqSOjf0qD5cf
  // f:+icon:assign_var:Th_Mpjao_oLzpEoRTVOJV
  state.config = config.clone();
  // f:-icon:assign_var:Th_Mpjao_oLzpEoRTVOJV
  // f:+icon:call_function:coMU79dt42juxXxaI9V0v
  let mut newColors: crate::falang::State::Colors = crate::falang::getColors::getColors(_apis);
  // f:-icon:call_function:coMU79dt42juxXxaI9V0v
  // f:+icon:assign_var:fda4Yx38op-Pn320kZ_6v
  state.colors = newColors.clone();
  // f:-icon:assign_var:fda4Yx38op-Pn320kZ_6v
  // f:+icon:call_function:nOIj_tm-8R6736W1G7rjN
  let mut snakePoint: crate::falang::State::Point = crate::falang::getRandomPoint::getRandomPoint(&state, _apis);
  // f:-icon:call_function:nOIj_tm-8R6736W1G7rjN
  // f:+icon:assign_var:xHRB4msL6yFfuxGSolU3G
  state.snake.x = snakePoint.x;
  // f:-icon:assign_var:xHRB4msL6yFfuxGSolU3G
  // f:+icon:assign_var:_oMa_qBHodtiQ4yEPqpa9
  state.snake.y = snakePoint.y;
  // f:-icon:assign_var:_oMa_qBHodtiQ4yEPqpa9
  // f:+icon:call_function:EhpuZbl6e0pnIeusCa_5M
  let mut foodPoint: crate::falang::State::Point = crate::falang::getNewFoodPoint::getNewFoodPoint(&state, _apis);
  // f:-icon:call_function:EhpuZbl6e0pnIeusCa_5M
  // f:+icon:assign_var:_DlmnAOHP64qjn_EByQNh
  state.food = foodPoint.clone();
  // f:-icon:assign_var:_DlmnAOHP64qjn_EByQNh
  // f:+icon:arr_push:OBURwlMvvVzKS56ghPw54
  state.snake.body.push(snakePoint.clone());
  // f:-icon:arr_push:OBURwlMvvVzKS56ghPw54
  // f:+icon:call_function:eBkdfxI8XgcEG6gW_bbKD
  crate::falang::clearScreen::clearScreen(&state, _apis);
  // f:-icon:call_function:eBkdfxI8XgcEG6gW_bbKD
  // f:+icon:call_function:Wnjqt6u201-28OxXrjqIF
  crate::falang::DrawFood::DrawFood(&state, _apis);
  // f:-icon:call_function:Wnjqt6u201-28OxXrjqIF
  // f:+icon:call_function:n7geuiwQBL18fzr6wSd7E
  crate::falang::drawSnakeSquare::drawSnakeSquare(&snakePoint, &state.colors.cellColor, &state.config, _apis);
  // f:-icon:call_function:n7geuiwQBL18fzr6wSd7E
  // f:+icon:while:LVIjyQVeO9DbTqBLWS4QN
  loop {
    // f:+icon:call_api:OTH3M7nL6TwI2m6UqC_uq
    _apis.GameApi_Application_Sleep();
    // f:-icon:call_api:OTH3M7nL6TwI2m6UqC_uq
    // f:+icon:call_api:73HZd8WnmnnaowYkSyW2Y
    let mut buttons: crate::falang::State::ButtonsState = _apis.GameApi_Application_GetButtonsState();
    // f:-icon:call_api:73HZd8WnmnnaowYkSyW2Y
    // f:+icon:if:N3P--yhZiBDqmqpPO9ZaL
    if buttons.left {
      // f:+icon:if:20ZJL1qnLFgtA471QN1nm
      if state.snake.dirX == (1) as i32 {
      } else {
        // f:+icon:assign_var:lsKFPHiFUnvBV8xZQYqRs
        state.snake.dirX = -(1) as i32;
        // f:-icon:assign_var:lsKFPHiFUnvBV8xZQYqRs
        // f:+icon:assign_var:g02JFtOlwKkKeDKyb8iH2
        state.snake.dirY = (0) as i32;
        // f:-icon:assign_var:g02JFtOlwKkKeDKyb8iH2
      }
      // f:-icon:if:20ZJL1qnLFgtA471QN1nm
    } else {
      // f:+icon:if:kUtdEpABwwB3FknbIIlYi
      if buttons.right {
        // f:+icon:if:xPkvSV53hUz6pJxFRFeG9
        if state.snake.dirX == -(1) as i32 {
        } else {
          // f:+icon:assign_var:xiWo2aSAyaSAAeXILMzIE
          state.snake.dirX = (1) as i32;
          // f:-icon:assign_var:xiWo2aSAyaSAAeXILMzIE
          // f:+icon:assign_var:guBRV_MOEO6dbL-ZOlhk9
          state.snake.dirY = (0) as i32;
          // f:-icon:assign_var:guBRV_MOEO6dbL-ZOlhk9
        }
        // f:-icon:if:xPkvSV53hUz6pJxFRFeG9
      } else {
        // f:+icon:if:Ah1YgblPJpw6h5fKYsYa1
        if buttons.top {
          // f:+icon:if:4JFaZJSrvfDVbhDRaarp6
          if state.snake.dirY == (1) as i32 {
          } else {
            // f:+icon:assign_var:S8dQHEOvfnZXgXNaYJQC_
            state.snake.dirX = (0) as i32;
            // f:-icon:assign_var:S8dQHEOvfnZXgXNaYJQC_
            // f:+icon:assign_var:Ox3hhZRJfg5FMflfFY1fF
            state.snake.dirY = -(1) as i32;
            // f:-icon:assign_var:Ox3hhZRJfg5FMflfFY1fF
          }
          // f:-icon:if:4JFaZJSrvfDVbhDRaarp6
        } else {
          // f:+icon:if:z4HPvsk14oGd6gHgAjt7P
          if buttons.bottom {
            // f:+icon:if:csOMo5j2PD6An5PwEohKm
            if state.snake.dirY == -(1) as i32 {
            } else {
              // f:+icon:assign_var:71w6gNOkzKiPSYNUWLWjT
              state.snake.dirX = (0) as i32;
              // f:-icon:assign_var:71w6gNOkzKiPSYNUWLWjT
              // f:+icon:assign_var:_7GjktgNfrD9E5efh77tA
              state.snake.dirY = (1) as i32;
              // f:-icon:assign_var:_7GjktgNfrD9E5efh77tA
            }
            // f:-icon:if:csOMo5j2PD6An5PwEohKm
          } else {
          }
          // f:-icon:if:z4HPvsk14oGd6gHgAjt7P
        }
        // f:-icon:if:Ah1YgblPJpw6h5fKYsYa1
      }
      // f:-icon:if:kUtdEpABwwB3FknbIIlYi
    }
    // f:-icon:if:N3P--yhZiBDqmqpPO9ZaL
    // f:+icon:if:BjtdWWmhwWBdMi4lJa4EW
    if state.snake.dirX == 0 && state.snake.dirY == 0 {
      continue;
    } else {
    }
    // f:-icon:if:BjtdWWmhwWBdMi4lJa4EW
    // f:+icon:call_function:y-82umpcjj0E7E0aBNTDm
    let mut nextPoint: crate::falang::State::Point = crate::falang::getNextPoint::getNextPoint(&state, _apis);
    // f:-icon:call_function:y-82umpcjj0E7E0aBNTDm
    // f:+icon:assign_var:pXy2D1myY3LaVRIJSAupb
    state.snake.x = nextPoint.x;
    // f:-icon:assign_var:pXy2D1myY3LaVRIJSAupb
    // f:+icon:assign_var:IlIanWUjpVergZAeeiZm2
    state.snake.y = nextPoint.y;
    // f:-icon:assign_var:IlIanWUjpVergZAeeiZm2
    // f:+icon:call_function:f9UwUDTP1olgYfu5K74hm
    let mut isOver: bool = crate::falang::isGameOver::isGameOver(&state, _apis);
    // f:-icon:call_function:f9UwUDTP1olgYfu5K74hm
    // f:+icon:if:7_4sZYSpK5CzmHEIvLWLg
    if isOver {
      // f:+icon:assign_var:dPjGRiBJLvEeDTX5xbzHu
      state.snake.dirX = (0) as i32;
      // f:-icon:assign_var:dPjGRiBJLvEeDTX5xbzHu
      // f:+icon:assign_var:9mwS3yc9mrNMP2M-P2sAS
      state.snake.dirY = (0) as i32;
      // f:-icon:assign_var:9mwS3yc9mrNMP2M-P2sAS
      // f:+icon:call_function:c65HhdmoFu1GpnNNWLWkB
      let mut newSnakePoint: crate::falang::State::Point = crate::falang::getRandomPoint::getRandomPoint(&state, _apis);
      // f:-icon:call_function:c65HhdmoFu1GpnNNWLWkB
      // f:+icon:assign_var:leLkEbFVQW87YHakHfFAX
      state.snake.body = vec![ newSnakePoint.clone() ];
      // f:-icon:assign_var:leLkEbFVQW87YHakHfFAX
      // f:+icon:call_function:NM0MNlvryEsXtu58IKDgs
      let mut newFoodPoint: crate::falang::State::Point = crate::falang::getNewFoodPoint::getNewFoodPoint(&state, _apis);
      // f:-icon:call_function:NM0MNlvryEsXtu58IKDgs
      // f:+icon:assign_var:578E6v0c9I0hRO6o1PDP-
      state.food = newFoodPoint.clone();
      // f:-icon:assign_var:578E6v0c9I0hRO6o1PDP-
      // f:+icon:call_api:gMinsGFaFQQkv-SiXdT-6
      _apis.GameApi_Drawing_DrawRect((0) as i32, (0) as i32, state.config.cellSize * state.config.gameWidth, state.config.cellSize * state.config.gameHeight, &state.colors.foodColor);
      // f:-icon:call_api:gMinsGFaFQQkv-SiXdT-6
      // f:+icon:call_function:vAg5y8j3yLm0eRIQollqL
      crate::falang::clearScreen::clearScreen(&state, _apis);
      // f:-icon:call_function:vAg5y8j3yLm0eRIQollqL
      // f:+icon:call_function:oejSVBSOo4shgFcVcvqE4
      crate::falang::DrawFood::DrawFood(&state, _apis);
      // f:-icon:call_function:oejSVBSOo4shgFcVcvqE4
      // f:+icon:call_function:LnM4pGU1fzaM7VEO8SQXD
      crate::falang::drawSnakeSquare::drawSnakeSquare(&newSnakePoint, &state.colors.cellColor, &state.config, _apis);
      // f:-icon:call_function:LnM4pGU1fzaM7VEO8SQXD
    } else {
      // f:+icon:arr_unshift:GG75qN8xmI5WV4ATpE8Db
      state.snake.body.insert(0, nextPoint.clone());
      // f:-icon:arr_unshift:GG75qN8xmI5WV4ATpE8Db
      // f:+icon:call_function:d9Xp7CDH4kEYpSWrcd6S2
      crate::falang::drawSnakeSquare::drawSnakeSquare(&nextPoint, &state.colors.cellColor, &state.config, _apis);
      // f:-icon:call_function:d9Xp7CDH4kEYpSWrcd6S2
      // f:+icon:if:J8FssgibapviRe1t0KXfw
      if state.snake.x == state.food.x && state.snake.y == state.food.y {
        // f:+icon:call_function:Naa9RR5i-Vl_AfGCf0jqz
        let mut newFoodPoint: crate::falang::State::Point = crate::falang::getNewFoodPoint::getNewFoodPoint(&state, _apis);
        // f:-icon:call_function:Naa9RR5i-Vl_AfGCf0jqz
        // f:+icon:assign_var:pjozbbcGA5eFaGMIRd4tZ
        state.food = newFoodPoint.clone();
        // f:-icon:assign_var:pjozbbcGA5eFaGMIRd4tZ
        // f:+icon:call_function:_kbNGeEvINMqUxodF4N6Z
        crate::falang::DrawFood::DrawFood(&state, _apis);
        // f:-icon:call_function:_kbNGeEvINMqUxodF4N6Z
      } else {
        // f:+icon:arr_pop:GzFhOMMQf-nGEF0KwIHUZ
        let mut oldPoint = state.snake.body.pop().unwrap();
        // f:-icon:arr_pop:GzFhOMMQf-nGEF0KwIHUZ
        // f:+icon:call_function:w49QyhSyqKkNDpzGmoRjy
        crate::falang::drawSnakeSquare::drawSnakeSquare(&oldPoint, &state.colors.backgroundColor, &state.config, _apis);
        // f:-icon:call_function:w49QyhSyqKkNDpzGmoRjy
        // f:+icon:call_api:SrriDRS3uorPptX9WCEhs
        _apis.GameApi_Drawing_DrawCircle(oldPoint.x * state.config.cellSize + state.config.cellSize / (2) as i32, oldPoint.y * state.config.cellSize + state.config.cellSize / (2) as i32, state.config.pointRadius, &state.colors.pointColor);
        // f:-icon:call_api:SrriDRS3uorPptX9WCEhs
      }
      // f:-icon:if:J8FssgibapviRe1t0KXfw
    }
    // f:-icon:if:7_4sZYSpK5CzmHEIvLWLg
  if !true { break; }
  }
  // f:-icon:while:LVIjyQVeO9DbTqBLWS4QN
  
}
// f:-icon:function:lB5upikdDh_HbhKEy2jH0

