/**
 * Generated by Falang
 * Document: State
 * Id: kHyjfyZ38T2JD3yH7pzN3
 **/
#[allow(non_snake_case)]
#[allow(unused_mut)]
// f:+icon:tree:m7IMRm5qZTdS75rvJ0-02
#[derive(Clone)]
pub struct Point {
  pub x: i32,
  pub y: i32,
}
impl Point {
  pub fn new() -> Point {
    Point {
      x: (0) as i32,
      y: (0) as i32,
    }
  }
}
#[derive(Clone)]
pub struct Snake {
  pub x: i32,
  pub y: i32,
  pub dirX: i32,
  pub dirY: i32,
  pub body: alloc::vec::Vec<crate::falang::State::Point>,
}
impl Snake {
  pub fn new() -> Snake {
    Snake {
      x: (0) as i32,
      y: (0) as i32,
      dirX: (0) as i32,
      dirY: (0) as i32,
      body: vec![],
    }
  }
}
#[derive(Clone)]
pub struct Color {
  pub r: i32,
  pub g: i32,
  pub b: i32,
}
impl Color {
  pub fn new() -> Color {
    Color {
      r: (0) as i32,
      g: (0) as i32,
      b: (0) as i32,
    }
  }
}
#[derive(Clone)]
pub struct Config {
  pub cellSize: i32,
  pub foodSize: i32,
  pub pointRadius: i32,
  pub gameWidth: i32,
  pub gameHeight: i32,
}
impl Config {
  pub fn new() -> Config {
    Config {
      cellSize: (0) as i32,
      foodSize: (0) as i32,
      pointRadius: (0) as i32,
      gameWidth: (0) as i32,
      gameHeight: (0) as i32,
    }
  }
}
#[derive(Clone)]
pub struct Colors {
  pub foodColor: crate::falang::State::Color,
  pub cellColor: crate::falang::State::Color,
  pub pointColor: crate::falang::State::Color,
  pub backgroundColor: crate::falang::State::Color,
}
impl Colors {
  pub fn new() -> Colors {
    Colors {
      foodColor: crate::falang::State::Color::new(),
      cellColor: crate::falang::State::Color::new(),
      pointColor: crate::falang::State::Color::new(),
      backgroundColor: crate::falang::State::Color::new(),
    }
  }
}
#[derive(Clone)]
pub struct ButtonsState {
  pub left: bool,
  pub right: bool,
  pub top: bool,
  pub bottom: bool,
}
impl ButtonsState {
  pub fn new() -> ButtonsState {
    ButtonsState {
      left: false,
      right: false,
      top: false,
      bottom: false,
    }
  }
}
#[derive(Clone)]
pub struct GameState {
  pub colors: crate::falang::State::Colors,
  pub snake: crate::falang::State::Snake,
  pub food: crate::falang::State::Point,
  pub config: crate::falang::State::Config,
}
impl GameState {
  pub fn new() -> GameState {
    GameState {
      colors: crate::falang::State::Colors::new(),
      snake: crate::falang::State::Snake::new(),
      food: crate::falang::State::Point::new(),
      config: crate::falang::State::Config::new(),
    }
  }
}
// f:-icon:tree:m7IMRm5qZTdS75rvJ0-02

